#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
"""
TT Local Video Generator
========================
GTK4 GUI for generating videos with Wan2.2-T2V-A14B-Diffusers via a local
tt-inference-server instance. Tracks generation history and supports iteration.

Usage:
    python3 main.py [--server http://localhost:8000]

Requires system python3-gi (GTK4 bindings) — install via:
    sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-4.0
"""
import argparse
import os
import resource
import sys
from pathlib import Path

# Disable GStreamer's VA-API hardware video decoders BEFORE GTK/GStreamer
# initialises.  The AMD radeonsi VA-API backend JIT-compiles GPU shaders via
# LLVM; under rapid pipeline open/close (attractor mode cycling every ~5 s)
# this hits a null-pointer dereference in libLLVM.so.20 and segfaults the
# whole process.  Setting these features to rank NONE forces GStreamer to use
# avdec_h264/avdec_h265 (libav software decode) instead, which is stable.
# The 5-second videos generated by Wan2.2 are small enough that software
# decode has negligible CPU overhead on a Ryzen 7 9700X.
os.environ.setdefault(
    "GST_PLUGIN_FEATURE_RANK",
    "vah264dec:NONE,vah265dec:NONE,vavp9dec:NONE,vaav1dec:NONE,"
    "vajpegdec:NONE,vacompositor:NONE,vadeinterlace:NONE,"
    "vah264enc:NONE,vah265enc:NONE",
)

# Raise the open-file descriptor limit early.  GStreamer video pipelines each
# hold ~40–80 fds (epoll, wakeup pipes, PulseAudio sockets, per-thread eventfds).
# The kernel default soft limit of 1024 is easily exhausted when a gallery with
# many cards has hover-previews open, or when the attractor cycles rapidly.
# We request 4096; cap at the hard limit (typically 4096 or unlimited = 1048576).
try:
    _soft, _hard = resource.getrlimit(resource.RLIMIT_NOFILE)
    if _soft < 4096:
        resource.setrlimit(resource.RLIMIT_NOFILE, (min(_hard, 4096), _hard))
except (ValueError, OSError):
    pass  # non-fatal; the app will still run, just with less headroom

import gi
gi.require_version("Gtk", "4.0")
gi.require_version("GdkPixbuf", "2.0")
from gi.repository import Gtk, Gio, GdkPixbuf

from main_window import MainWindow

# Path to the bundled Tenstorrent icon (32×32 PNG, fetched from tenstorrent.com)
_ICON_PATH = Path(__file__).parent / "assets" / "tenstorrent.png"


def main():
    parser = argparse.ArgumentParser(description="TT Local Video Generator")
    parser.add_argument(
        "--server",
        default="http://localhost:8000",
        help="tt-inference-server base URL (default: http://localhost:8000)",
    )
    # GTK consumes its own argv; parse known args only so GTK flags don't cause errors
    args, gtk_args = parser.parse_known_args()

    app = Gtk.Application(application_id="ai.tenstorrent.tt-video-gen")
    # Allow multiple instances — avoids silent no-op when an existing session-bus
    # registration is present (e.g. a stale process or a second launch).
    app.set_flags(Gio.ApplicationFlags.NON_UNIQUE)

    def on_activate(application):
        win = MainWindow(app=application, server_url=args.server)
        # Set window icon from bundled asset; fall back gracefully if missing.
        if _ICON_PATH.exists():
            try:
                pixbuf = GdkPixbuf.Pixbuf.new_from_file(str(_ICON_PATH))
                win.set_icon_name("ai.tenstorrent.tt-video-gen")  # XDG name
                # GTK4 uses the application icon; set it via the display's
                # default icon list as a pixbuf fallback.
                Gtk.Window.set_default_icon_name("ai.tenstorrent.tt-video-gen")
            except Exception:
                pass
        win.present()

    app.connect("activate", on_activate)
    sys.exit(app.run([sys.argv[0]] + gtk_args))


if __name__ == "__main__":
    main()
