#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
"""
TT Local Video Generator
========================
GTK4 GUI for generating videos with Wan2.2-T2V-A14B-Diffusers via a local
tt-inference-server instance. Tracks generation history and supports iteration.

Usage:
    python3 main.py [--server http://localhost:8000]

Requires system python3-gi (GTK4 bindings) — install via:
    sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-4.0
"""
import argparse
import os
import resource
import sys
from pathlib import Path

# Disable GStreamer's VA-API hardware video decoders BEFORE GTK/GStreamer
# initialises.  Linux-only: VA-API doesn't exist on macOS and setting the
# feature rank for non-existent plugins is harmless, but keeping this
# Linux-scoped avoids any risk of interfering with macOS GStreamer setup.
#
# The AMD radeonsi VA-API backend JIT-compiles GPU shaders via LLVM; under
# rapid pipeline open/close (attractor mode cycling every ~5 s) this hits a
# null-pointer dereference in libLLVM.so.20 and segfaults the process.
# Setting these features to rank NONE forces avdec_h264/avdec_h265 (libav
# software decode) which is stable.  The 5-second videos generated by
# Wan2.2 are small enough that software decode has negligible CPU overhead.
import platform as _platform
if _platform.system() == "Linux":
    os.environ.setdefault(
        "GST_PLUGIN_FEATURE_RANK",
        "vah264dec:NONE,vah265dec:NONE,vavp9dec:NONE,vaav1dec:NONE,"
        "vajpegdec:NONE,vacompositor:NONE,vadeinterlace:NONE,"
        "vah264enc:NONE,vah265enc:NONE",
    )

# Raise the open-file descriptor limit early.  GStreamer video pipelines each
# hold ~40–80 fds (epoll, wakeup pipes, PulseAudio sockets, per-thread eventfds).
# The kernel default soft limit of 1024 is easily exhausted when a gallery with
# many cards has hover-previews open, or when the attractor cycles rapidly.
# We request 4096; cap at the hard limit (typically 4096 or unlimited = 1048576).
try:
    _soft, _hard = resource.getrlimit(resource.RLIMIT_NOFILE)
    if _soft < 4096:
        resource.setrlimit(resource.RLIMIT_NOFILE, (min(_hard, 4096), _hard))
except (ValueError, OSError):
    pass  # non-fatal; the app will still run, just with less headroom

import gi
gi.require_version("Gtk", "4.0")
gi.require_version("GdkPixbuf", "2.0")
from gi.repository import Gtk, Gio, GdkPixbuf

from main_window import MainWindow

# Path to the bundled Tenstorrent icon (32×32 PNG, fetched from tenstorrent.com)
_ICON_PATH = Path(__file__).parent / "assets" / "tenstorrent.png"

_LOCALHOST = {"localhost", "127.0.0.1"}


def _derive_prompt_url(server_url: str) -> str:
    """
    Derive the prompt-server base URL from the inference server URL.

    Assumes the Qwen prompt server runs on the same host at port 8001.
    Returns the default local URL unchanged when server_url is localhost.
    """
    from urllib.parse import urlparse
    parsed = urlparse(server_url)
    host = parsed.hostname or "localhost"
    if host in _LOCALHOST:
        return "http://127.0.0.1:8001"
    return f"http://{host}:8001"


def _derive_inventory_url(server_url: str) -> str:
    """
    Derive the inventory server URL from the inference server URL.

    The inventory server (tt-ctl serve-inventory) runs on the same host at
    port 8002.  Returns an empty string for localhost so the GUI only fetches
    remote inventory when --server actually points at a remote machine.
    """
    from urllib.parse import urlparse
    parsed = urlparse(server_url)
    host = parsed.hostname or "localhost"
    if host in _LOCALHOST:
        return ""   # no remote inventory for local-only mode
    return f"http://{host}:8002"


def _apply_remote_host_to_config(server_url: str) -> None:
    """
    When --server points at a non-localhost host, update all service entries in
    server_config that still have localhost/127.0.0.1 so that the Preferences
    dialog reflects the remote host and health checks use the right addresses.
    Writes through to ~/.config/tt-video-gen/servers.json immediately.
    """
    from urllib.parse import urlparse
    from server_config import server_config as _sc
    host = urlparse(server_url).hostname or "localhost"
    if host not in _LOCALHOST:
        _sc.apply_remote_host(host)


def main():
    parser = argparse.ArgumentParser(description="TT Local Video Generator")
    parser.add_argument(
        "--server",
        default="http://localhost:8000",
        help="tt-inference-server base URL (default: http://localhost:8000)",
    )
    # GTK consumes its own argv; parse known args only so GTK flags don't cause errors
    args, gtk_args = parser.parse_known_args()

    app = Gtk.Application(application_id="ai.tenstorrent.tt-video-gen")
    # Allow multiple instances — avoids silent no-op when an existing session-bus
    # registration is present (e.g. a stale process or a second launch).
    app.set_flags(Gio.ApplicationFlags.NON_UNIQUE)

    def on_activate(application):
        # Request the dark variant of the current GTK theme.  This is a no-op
        # on Linux when the system theme is already dark (KDE/GNOME dark mode),
        # but is essential on macOS where GTK defaults to Adwaita Light and
        # leaves un-CSS'd widgets (dialogs, native buttons, popovers) white.
        try:
            gtk_settings = Gtk.Settings.get_default()
            if gtk_settings:
                gtk_settings.set_property("gtk-application-prefer-dark-theme", True)
        except Exception:
            pass

        # Register the "quit" action on the application object so that menu
        # items using "app.quit" work.  Gtk.Application does NOT register this
        # automatically — it must be added explicitly.
        quit_action = Gio.SimpleAction.new("quit", None)
        quit_action.connect("activate", lambda *_: application.quit())
        application.add_action(quit_action)

        # Register the bundled assets/ directory as an icon search path so
        # the Tenstorrent icon is found by name on every window — including
        # secondary windows (Attractor, fullscreen player) — without requiring
        # setup_ubuntu.sh to have installed the icon into the XDG icon cache.
        if _ICON_PATH.exists():
            try:
                from gi.repository import Gdk
                display = Gdk.Display.get_default()
                if display:
                    theme = Gtk.IconTheme.get_for_display(display)
                    theme.add_search_path(str(_ICON_PATH.parent))
            except Exception:
                pass
        Gtk.Window.set_default_icon_name("ai.tenstorrent.tt-video-gen")

        win = MainWindow(
            app=application,
            server_url=args.server,
            prompt_server_url=_derive_prompt_url(args.server),
            inventory_url=_derive_inventory_url(args.server),
        )
        win.present()

    # Update persisted server config so Preferences shows the right host/port
    # and the prompt-server health check hits the correct address.
    _apply_remote_host_to_config(args.server)

    app.connect("activate", on_activate)
    sys.exit(app.run([sys.argv[0]] + gtk_args))


if __name__ == "__main__":
    main()
